server:
  port: 8889
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: myhc
  banner:
    location: banner.text
  servlet:
    multipart:
      max-file-size: 5MB #允许上传文件总单最大值
      max-request-size: 50MB #允许上传文件总的最大值
  datasource:
    name: dataSource-default
    url: jdbc:mysql://localhost:3307/hc
    type: com.alibaba.druid.pool.DruidDataSource
    username: root #sa
    password: 1234567
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 3 # 初始化大小
    minIdle: 3 #最小连接池数量
    maxActive: 20 #最大连接池数量
    timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 #验证连接有效与否的SQL
    testWhileIdle: true #不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testOnBorrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    filters: stat # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  thymeleaf:   #thymeleaf配置
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5   #LEGACYHTML5
    cache: true
  mvc:
    static-path-pattern: "/static/**"

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    cache-enabled: true  #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    callSettersOnNulls: true
  global-config:
    banner: false
    db-config:
      id-type: AUTO   #数据库自增
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-aliases-package: com.example.myhc.domain   # 实体扫描，多个package用逗号或者分号分隔
  typeEnumsPackage: com.example.myhc.enums
